In [1]:
import numpy as np
import pandas as pd

In [16]:
titanic_train = pd.read_csv('train.csv')

In [ ]:
titanic_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
char_cabin = titanic_train['Cabin'].astype(str)


new_cabin = np.array(cabin[0] for cabin in char_cabin)


titanic_train['Cabin'] = new_cabin

In [19]:
titanic_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,n,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,n,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,n,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,n,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,n,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,n,Q

In [46]:
my_tab = pd.crosstab(index = titanic_train['Survived'], columns= ['count'])         
my_tab

col_0     count
Survived
0           549
1           342

In [47]:
type(my_tab)

pandas.core.frame.DataFrame

In [48]:
pd.crosstab(index = titanic_train['Cabin'], columns = titanic_train['Survived'])

Survived    0    1
Cabin
A           8    7
B          12   35
C          24   35
D           8   25
E           8   24
F           5    8
G           2    2
T           1    0
n         481  206

In [49]:
pd.crosstab(titanic_train['Cabin'], titanic_train['Survived'], margins=True)

Survived    0    1  All
Cabin
A           8    7   15
B          12   35   47
C          24   35   59
D           8   25   33
E           8   24   32
F           5    8   13
G           2    2    4
T           1    0    1
n         481  206  687
All       549  342  891

In [50]:
pd.crosstab(index = titanic_train['Pclass'], columns = ['count'])

col_0   count
Pclass
1         216
2         184
3         491

In [51]:
titanic_trains.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [73]:
cabin_tab = pd.crosstab(index = titanic_train['Cabin'], columns = ['count'])

cabin_tab

col_0  count
Cabin
A         15
B         47
C         59
D         33
E         32
F         13
G          4
T          1
n        687

In [62]:
print(cabin_tab.sum(), "\n")
print(cabin_tab.shape, "\n")

col_0
count    891
dtype: int64

(9, 1)

In [75]:
cabin_tab/cabin_tab.sum()

col_0     count
Cabin
A      0.016835
B      0.052750
C      0.066218
D      0.037037
E      0.035915
F      0.014590
G      0.004489
T      0.001122
n      0.771044

In [67]:
survived_class = pd.crosstab(titanic_train['Survived'], titanic_train['Pclass'], margins=True)

survived_class.columns = ['Class 1', 'Class 2', 'Class 3', 'rowTotals']
survived_class.index = ['Died', 'Survived', 'colTotals']

survived_class

           Class 1  Class 2  Class 3  rowTotals
Died            80       97      372        549
Survived       136       87      119        342
colTotals      216      184      491        891

In [109]:
survived_class/survived_class.loc['colTotals','rowTotals']

            Class 1   Class 2   Class 3  rowTotals
Died       0.089787  0.108866  0.417508   0.616162
Survived   0.152637  0.097643  0.133558   0.383838
colTotals  0.242424  0.206510  0.551066   1.000000

In [111]:
survived_class.loc['colTotals']

Class 1      216
Class 2      184
Class 3      491
rowTotals    891
Name: colTotals, dtype: int64

In [112]:
survived_class/survived_class.loc['colTotals']

           Class 1   Class 2   Class 3  rowTotals
Died       0.37037  0.527174  0.757637   0.616162
Survived   0.62963  0.472826  0.242363   0.383838
colTotals  1.00000  1.000000  1.000000   1.000000

In [117]:
survived_class.div(survived_class.loc['colTotals'])

           Class 1   Class 2   Class 3  rowTotals
Died       0.37037  0.527174  0.757637   0.616162
Survived   0.62963  0.472826  0.242363   0.383838
colTotals  1.00000  1.000000  1.000000   1.000000

In [127]:
survived_class.div(survived_class['rowTotals'], axis=0)

            Class 1   Class 2   Class 3  rowTotals
Died       0.145719  0.176685  0.677596        1.0
Survived   0.397661  0.254386  0.347953        1.0
colTotals  0.242424  0.206510  0.551066        1.0

In [129]:
survived_class.T/survived_class.T.loc['rowTotals']

               Died  Survived  colTotals
Class 1    0.145719  0.397661   0.242424
Class 2    0.176685  0.254386   0.206510
Class 3    0.677596  0.347953   0.551066
rowTotals  1.000000  1.000000   1.000000

In [ ]:
surv_sex_class = pd.crosstab(index = titanic_train['Survived'] 
                             , columns = [titanic_train['Pclass'], titanic_train['Sex']]
                             , margins = True
                             )

surv_sex_class

Pclass        1           2           3       All
Sex      female male female male female male
Survived
0             3   77      6   91     72  300  549
1            91   45     70   17     72   47  342
All          94  122     76  108    144  347  891

In [150]:
surv_sex_class[2]['female']

Survived
0       6
1      70
All    76
Name: female, dtype: int64

In [ ]:

# SÓ PARA RELEMBRAR COMO O LOC FUNCIONA COMO UM "WHERE" NO SQL

titanic_train.loc[titanic_trains['PassengerId'] < 5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,n,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,n,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S